/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.iglojpa;

import id.co.indocyber.iglojpa.controller.PersonController;
import id.co.indocyber.iglojpa.model.Person;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author user
 */
public class PersonApp extends javax.swing.JFrame {

    ApplicationContext context = new ClassPathXmlApplicationContext("SpringBeans.xml");
    private PersonController personControl;
    NewPersonForm nperson = new NewPersonForm();

    /**
     * Creates new form PersonApp
     */
    public PersonApp() {
        initComponents();
//        emf = Persistence.createEntityManagerFactory("igloJPAPU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        refreshMenu = new javax.swing.JMenuItem();
        closeMenuPop = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        searchTxtField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newPersonMenu = new javax.swing.JMenuItem();
        showPersonMenu = new javax.swing.JMenuItem();
        deletePersonMenu = new javax.swing.JMenu();

        refreshMenu.setText("Refresh Table");
        refreshMenu.setActionCommand("Refresh Table");
        refreshMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMenuActionPerformed(evt);
            }
        });
        popMenu.add(refreshMenu);

        closeMenuPop.setText("Close");
        popMenu.add(closeMenuPop);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Person");

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainPanelMouseReleased(evt);
            }
        });

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Person", "Name", "Age", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                personTableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                personTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(personTable);
        if (personTable.getColumnModel().getColumnCount() > 0) {
            personTable.getColumnModel().getColumn(0).setResizable(false);
            personTable.getColumnModel().getColumn(1).setResizable(false);
            personTable.getColumnModel().getColumn(2).setResizable(false);
            personTable.getColumnModel().getColumn(3).setResizable(false);
        }

        searchTxtField.setText("Search");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTxtField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        newPersonMenu.setText("New Person");
        newPersonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPersonMenuActionPerformed(evt);
            }
        });
        jMenu1.add(newPersonMenu);

        showPersonMenu.setText("Show Data Person");
        showPersonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPersonMenuActionPerformed(evt);
            }
        });
        jMenu1.add(showPersonMenu);

        jMenuBar1.add(jMenu1);

        deletePersonMenu.setText("Delete");
        jMenuBar1.add(deletePersonMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPersonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPersonMenuActionPerformed
        // TODO add your handling code here:
//        mainPanel.setVisible(false);
        nperson.setVisible(true);
        nperson.nameTxtField.requestFocus();
    }//GEN-LAST:event_newPersonMenuActionPerformed

    private void showPersonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPersonMenuActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_showPersonMenuActionPerformed

    private void refreshTable(){
        DefaultTableModel tableModel = (DefaultTableModel) personTable.getModel();
        tableModel.setRowCount(0);
        showPeople();
    }
    
    private void personTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personTableMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            popMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_personTableMouseReleased

    private void personTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personTableMousePressed
        // TODO add your handling code here:
//        if(evt.isPopupTrigger()){
//            popMenu.show(this, evt.getX(), evt.getY());
//        }
    }//GEN-LAST:event_personTableMousePressed

    private void personTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personTableMouseClicked
        // TODO add your handling code here:
//        if(evt.isPopupTrigger()){
//            popMenu.show(this, evt.getX(), evt.getY());
//        }
    }//GEN-LAST:event_personTableMouseClicked

    private void refreshMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMenuActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_refreshMenuActionPerformed

    private void mainPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            popMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_mainPanelMouseReleased

    private void showPeople() {

        personControl = (PersonController) context.getBean("newPerson");
        List<Person> person = personControl.getPerson();
        DefaultTableModel tableModel = (DefaultTableModel) personTable.getModel();
        Object[] row = new Object[4];
        for (Person person1 : person) {
            row[0] = person1.getId();
            row[1] = person1.getName();
            row[2] = person1.getAge();
            row[3] = person1.getSalary();
            tableModel.addRow(row);
        }
//        tableModel.setRowCount(0);
        
//        ListSelectionModel rowSelectedModel = personTable.getSelectionModel();
//        rowSelectedModel
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeMenuPop;
    private javax.swing.JMenu deletePersonMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem newPersonMenu;
    public javax.swing.JTable personTable;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JMenuItem refreshMenu;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JMenuItem showPersonMenu;
    // End of variables declaration//GEN-END:variables
}
